"""Hybrid ViewPort — Design Token Bridge.

Syncs design-tokens.json (W3C DTCG) → CSS custom properties + theme.py marker.

    design-tokens.json
           │
           ├──► fleet/static/tokens.css        (CSS custom properties)
           ├──► BigEd/launcher/ui/theme.py      (generated-from-tokens marker)
           └──► figma-export/tokens-diff.json   (future: changelog for Figma re-import)

Usage:
    python fleet/token_bridge.py              # regenerate all outputs
    python fleet/token_bridge.py --check      # check staleness only
"""

import json
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger(__name__)

FLEET_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = FLEET_DIR.parent
TOKENS_PATH = PROJECT_ROOT / "design-tokens.json"
CSS_OUTPUT = FLEET_DIR / "static" / "tokens.css"

DEFAULT_THEME = "figma"


def _load_tokens(tokens_path: Path | None = None) -> dict:
    """Load and parse design-tokens.json."""
    path = tokens_path or TOKENS_PATH
    if not path.exists():
        raise FileNotFoundError(f"Token file not found: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def _extract_values(theme_dict: dict) -> dict[str, str]:
    """Extract token name → resolved value from a DTCG theme dict."""
    result = {}
    for key, token in theme_dict.items():
        if isinstance(token, dict) and "$value" in token:
            result[key] = token["$value"]
    return result


def _extract_group(group_dict: dict, prefix: str = "") -> dict[str, str]:
    """Recursively extract shared token groups into flat CSS variable names."""
    result = {}
    for key, val in group_dict.items():
        css_name = f"{prefix}-{key}" if prefix else key
        if isinstance(val, dict) and "$value" in val:
            result[css_name] = val["$value"]
        elif isinstance(val, dict):
            result.update(_extract_group(val, css_name))
    return result


def generate_css(tokens_path: Path | None = None) -> str:
    """Generate CSS custom properties from design-tokens.json."""
    tokens = _load_tokens(tokens_path)
    themes = tokens.get("themes", {})
    shared = tokens.get("shared", {})
    version = tokens.get("version", "unknown")

    lines = [
        f"/* BigEd Design Tokens — generated by token_bridge.py */",
        f"/* Source: design-tokens.json (version: {version}) */",
        f"/* Do not edit manually — edit design-tokens.json instead */",
        "",
    ]

    # Default theme (:root)
    default = themes.get(DEFAULT_THEME, {})
    default_vals = _extract_values(default)
    lines.append(":root {")
    for name, val in default_vals.items():
        lines.append(f"  --{name}: {val};")

    # Shared tokens (non-theme-specific)
    if shared:
        lines.append("")
        lines.append("  /* Shared tokens */")
        shared_flat = _extract_group(shared)
        for name, val in shared_flat.items():
            lines.append(f"  --{name}: {val};")

    lines.append("}")
    lines.append("")

    # Theme overrides
    for theme_name, theme_dict in themes.items():
        if theme_name == DEFAULT_THEME:
            continue
        vals = _extract_values(theme_dict)
        lines.append(f'[data-theme="{theme_name}"] {{')
        for name, val in vals.items():
            lines.append(f"  --{name}: {val};")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def write_css(output_path: Path | None = None, tokens_path: Path | None = None) -> Path:
    """Generate and write tokens.css."""
    out = output_path or CSS_OUTPUT
    os.makedirs(out.parent, exist_ok=True)
    css = generate_css(tokens_path)
    out.write_text(css, encoding="utf-8")
    log.info("token_bridge: wrote %s (%d bytes)", out, len(css))
    return out


def generate_theme_marker() -> str:
    """Return a comment block for theme.py indicating token sync status."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"# ─── Token Bridge ───────────────────────────────────────────────────────────\n"
        f"# Theme presets synced from design-tokens.json via fleet/token_bridge.py\n"
        f"# Last sync check: {now}\n"
        f"# Edit THEME_PRESETS here OR design-tokens.json — bridge keeps them aligned\n"
    )


def get_active_theme(theme_name: str = DEFAULT_THEME, tokens_path: Path | None = None) -> dict:
    """Read token values for a specific theme."""
    tokens = _load_tokens(tokens_path)
    theme_dict = tokens.get("themes", {}).get(theme_name, {})
    return _extract_values(theme_dict)


def check_staleness(tokens_path: Path | None = None) -> dict:
    """Check if generated outputs are older than the token file."""
    src = tokens_path or TOKENS_PATH
    if not src.exists():
        return {"stale": True, "reason": "token file missing"}

    src_mtime = src.stat().st_mtime
    results = {}
    for name, path in [("tokens.css", CSS_OUTPUT)]:
        if not path.exists():
            results[name] = {"stale": True, "reason": "file missing"}
        elif path.stat().st_mtime < src_mtime:
            results[name] = {"stale": True, "reason": "older than token file"}
        else:
            results[name] = {"stale": False}

    return results


def sync_all(tokens_path: Path | None = None) -> dict:
    """Regenerate all outputs from design-tokens.json."""
    results = {}
    try:
        css_path = write_css(tokens_path=tokens_path)
        results["tokens.css"] = {"status": "ok", "path": str(css_path)}
    except Exception:
        log.warning("token_bridge: failed to write tokens.css", exc_info=True)
        results["tokens.css"] = {"status": "error"}

    staleness = check_staleness(tokens_path)
    results["staleness"] = staleness
    return results


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if "--check" in sys.argv:
        staleness = check_staleness()
        for name, info in staleness.items():
            status = "STALE" if info.get("stale") else "OK"
            reason = info.get("reason", "")
            print(f"  {name}: {status} {reason}")
    else:
        print("Syncing design tokens...")
        results = sync_all()
        for name, info in results.items():
            if isinstance(info, dict) and "status" in info:
                print(f"  {name}: {info['status']}")
        print("Done.")
