"""
Curriculum update — analyzes completed work, skill gaps, and review findings
to rewrite idle curricula for coder agents.

Scans:
  1. Skill gap reports — which skills need creation
  2. Benchmark results — which skills need optimization
  3. Recent reviews — which files need follow-up
  4. Existing curricula — what's already covered

Payload:
  target_role   str   role to update curriculum for (e.g. "coder_1", "archivist")
                      default: updates all coder roles
  dry_run       bool  preview changes without writing (default true)

Output: fleet/idle_curricula/<role>.toml (updated)
Returns: {roles_updated, tasks_added, tasks_removed, preview}
"""
import re
import sys
from pathlib import Path

SKILL_NAME = "curriculum_update"
DESCRIPTION = "Curriculum update — analyzes completed work, skill gaps, and review findings"

FLEET_DIR = Path(__file__).parent.parent
CURRICULA_DIR = FLEET_DIR / "idle_curricula"
KNOWLEDGE_DIR = FLEET_DIR / "knowledge"
REPORTS_DIR = KNOWLEDGE_DIR / "reports"
SKILLS_DIR = FLEET_DIR / "skills"

sys.path.insert(0, str(FLEET_DIR))

PERSPECTIVES = {
    "coder_1": "software architect",
    "coder_2": "code critic / reviewer",
    "coder_3": "performance optimizer",
}


def _get_existing_skills() -> list[str]:
    return sorted(f.stem for f in SKILLS_DIR.glob("*.py") if not f.stem.startswith("_"))


def _get_gap_proposals() -> list[dict]:
    """Read the most recent skill gap report."""
    if not REPORTS_DIR.exists():
        return []
    reports = sorted(REPORTS_DIR.glob("skill_gaps_*.md"), reverse=True)
    if not reports:
        return []
    content = reports[0].read_text(errors="ignore")
    proposals = []
    for match in re.finditer(r"## \d+\.\s+(\S+)\s+\(priority (\d+)\)\s*\n\*\*Reason:\*\*\s*(.*?)\n\*\*Description:\*\*\s*(.*?)(?=\n## |\Z)", content, re.DOTALL):
        proposals.append({
            "name": match.group(1),
            "priority": int(match.group(2)),
            "reason": match.group(3).strip(),
            "description": match.group(4).strip(),
        })
    return proposals


def _get_benchmark_findings() -> list[str]:
    """Find skills with high error rates from benchmarks."""
    if not REPORTS_DIR.exists():
        return []
    slow = []
    for report in sorted(REPORTS_DIR.glob("benchmark_*.md"), reverse=True)[:5]:
        content = report.read_text(errors="ignore")
        match = re.search(r"Error rate: ([\d.]+)%", content)
        skill_match = re.search(r"Benchmark: `(\w+)`", content)
        if match and skill_match:
            rate = float(match.group(1))
            if rate > 20:
                slow.append(skill_match.group(1))
    return slow


def _generate_tasks(role: str, perspective: str, gaps: list, slow_skills: list) -> list[str]:
    """Generate TOML task entries for a role."""
    tasks = []

    # Skill drafts from gaps
    for gap in gaps[:3]:
        tasks.append(f"""
[[tasks]]
type = "skill_draft"
[tasks.payload]
agent_name = "{role}"
perspective = "{perspective}"
skill_name = "{gap['name']}"
description = "{gap['description'][:120]}"
""")

    # Skill evolve for underperforming skills
    for skill in slow_skills[:2]:
        tasks.append(f"""
[[tasks]]
type = "skill_evolve"
[tasks.payload]
skill_name = "{skill}"
perspective = "{perspective}"
agent_name = "{role}"
focus = "error handling and reliability"
""")

    # FMA review (keep existing)
    tasks.append(f"""
[[tasks]]
type = "fma_review"
[tasks.payload]
agent_name = "{role}"
perspective = "{perspective}"
mode = "discuss"
round = 1
""")

    return tasks


def run(payload, config):
    target_role = payload.get("target_role", "")
    dry_run = payload.get("dry_run", True)

    roles = [target_role] if target_role else list(PERSPECTIVES.keys())
    gaps = _get_gap_proposals()
    slow = _get_benchmark_findings()
    skills = _get_existing_skills()

    results = {}
    for role in roles:
        perspective = PERSPECTIVES.get(role, "generalist coder")
        new_tasks = _generate_tasks(role, perspective, gaps, slow)

        if dry_run:
            results[role] = {
                "tasks_proposed": len(new_tasks),
                "preview": "\n".join(new_tasks[:3]),
            }
        else:
            # Read existing curriculum
            toml_path = CURRICULA_DIR / f"{role}.toml"
            existing = toml_path.read_text() if toml_path.exists() else ""

            # Append new tasks (preserving existing)
            marker = "\n# ── Auto-generated by curriculum_update ──\n"
            # Remove old auto-generated section if present
            if marker in existing:
                existing = existing[:existing.index(marker)]

            updated = existing.rstrip() + "\n" + marker + "\n".join(new_tasks) + "\n"
            toml_path.write_text(updated)

            results[role] = {
                "tasks_added": len(new_tasks),
                "file": str(toml_path),
            }

    return {
        "roles_updated": list(results.keys()),
        "dry_run": dry_run,
        "skill_gaps": len(gaps),
        "slow_skills": slow,
        "details": results,
    }