"""
DT-4: Stability analysis — pattern detection on resolution data.
Reads data/resolutions.jsonl and produces stability reports.
"""
import json
from datetime import datetime
from pathlib import Path
from collections import Counter

SKILL_NAME = "stability_report"
DESCRIPTION = "Analyze resolution data for failure patterns, severity breakdown, and MTTR"
REQUIRES_NETWORK = False

FLEET_DIR = Path(__file__).parent.parent
RESOLUTIONS_PATH = FLEET_DIR / "data" / "resolutions.jsonl"
REPORTS_DIR = FLEET_DIR / "knowledge" / "reports"


def run(payload: dict, config: dict) -> str:
    """Analyze resolutions.jsonl and produce a stability report."""
    resolutions = _load_resolutions()

    if not resolutions:
        return json.dumps({
            "status": "no_data",
            "message": "No resolution data found. File: data/resolutions.jsonl"
        })

    analysis = _analyze(resolutions)
    report_md = _format_report(analysis, resolutions)

    # Save report
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    date_str = datetime.now().strftime("%Y%m%d")
    report_path = REPORTS_DIR / f"stability_report_{date_str}.md"
    report_path.write_text(report_md, encoding="utf-8")

    return json.dumps({
        "status": "ok",
        "total_resolutions": len(resolutions),
        "report_path": str(report_path),
        **analysis,
    })


def _load_resolutions():
    """Load resolutions from JSONL file."""
    if not RESOLUTIONS_PATH.exists():
        return []
    entries = []
    for line in RESOLUTIONS_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entries.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return entries


def _analyze(resolutions):
    """Run pattern detection queries on resolution data."""
    components = Counter(r.get("component", "unknown") for r in resolutions)
    severities = Counter(r.get("severity", "unknown") for r in resolutions)
    statuses = Counter(r.get("status", "unknown") for r in resolutions)

    # Platform distribution (platforms is a list field)
    platforms = Counter()
    for r in resolutions:
        for p in (r.get("platform") or []):
            platforms[p] += 1

    # Mean time to resolve (for entries with both timestamps)
    resolve_times = []
    for r in resolutions:
        if r.get("resolved_at") and r.get("report_id"):
            try:
                resolved = datetime.fromisoformat(r["resolved_at"].replace("Z", "+00:00"))
                # Use resolved_at as proxy; real MTTR would need reported_at
                resolve_times.append(resolved)
            except (ValueError, TypeError):
                pass

    return {
        "top_components": dict(components.most_common(5)),
        "severity_breakdown": dict(severities),
        "status_breakdown": dict(statuses),
        "platform_distribution": dict(platforms),
        "shipped_count": statuses.get("shipped", 0),
        "pending_count": statuses.get("pending", 0),
        "wontfix_count": statuses.get("wontfix", 0),
    }


def _format_report(analysis, resolutions):
    """Format analysis as a markdown stability report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# Stability Report — {now}",
        "",
        f"**Total resolutions:** {len(resolutions)}",
        f"**Shipped:** {analysis['shipped_count']} | "
        f"**Pending:** {analysis['pending_count']} | "
        f"**Won't Fix:** {analysis['wontfix_count']}",
        "",
        "## Top Failure Components",
        "",
        "| Component | Count |",
        "|-----------|-------|",
    ]
    for comp, count in sorted(analysis["top_components"].items(), key=lambda x: -x[1]):
        lines.append(f"| {comp} | {count} |")

    lines.extend([
        "",
        "## Severity Breakdown",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ])
    for sev in ["P0", "P1", "P2", "P3"]:
        count = analysis["severity_breakdown"].get(sev, 0)
        if count:
            lines.append(f"| {sev} | {count} |")

    lines.extend([
        "",
        "## Platform Distribution",
        "",
        "| Platform | Issues |",
        "|----------|--------|",
    ])
    for plat, count in sorted(analysis["platform_distribution"].items(), key=lambda x: -x[1]):
        lines.append(f"| {plat} | {count} |")

    lines.extend(["", "---", f"*Generated by fleet skill `{SKILL_NAME}`*", ""])
    return "\n".join(lines)
