"""
DT-4: Stability analysis — pattern detection on resolution data.
Reads data/resolutions.jsonl and produces stability reports.
"""
import json
from datetime import datetime
from pathlib import Path
from collections import Counter
import logging
from skills._knowledge import save_report, log_operation, ensure_in_index
from skills._report import ReportBuilder

SKILL_NAME = "stability_report"
DESCRIPTION = "Analyze resolution data for failure patterns, severity breakdown, and MTTR"
VERSION = "1.0.0"
COMPLEXITY = "simple"
REQUIRES_NETWORK = False
SUITE = "ops"
log = logging.getLogger(SKILL_NAME)

FLEET_DIR = Path(__file__).parent.parent
RESOLUTIONS_PATH = FLEET_DIR / "data" / "resolutions.jsonl"


def run(payload: dict, config: dict) -> dict:
    """Analyze resolutions.jsonl and produce a stability report."""
    resolutions = _load_resolutions()

    if not resolutions:
        return {
            "status": "no_data",
            "message": "No resolution data found. File: data/resolutions.jsonl"
        }

    analysis = _analyze(resolutions)
    report_md = _format_report(analysis, resolutions)

    try:
        report_path = save_report("reports", "stability_report", report_md)
    except Exception as e:
        return {
            "status": "error",
            "error": f"Report write failed: {e}",
            "total_resolutions": len(resolutions),
            **analysis,
        }

    # Wiki maintenance (WS-6)
    rel = str(report_path.relative_to(FLEET_DIR / "knowledge"))
    log_operation("stability_report", "ingest", f"stability report ({len(resolutions)} resolutions)")
    ensure_in_index(rel, "Stability Report", f"{len(resolutions)} resolutions analyzed")

    return {
        "status": "ok",
        "total_resolutions": len(resolutions),
        "report_path": str(report_path),
        **analysis,
    }


def _load_resolutions():
    """Load resolutions from JSONL file."""
    if not RESOLUTIONS_PATH.exists():
        return []
    entries = []
    for line in RESOLUTIONS_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entries.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return entries


def _analyze(resolutions):
    """Run pattern detection queries on resolution data."""
    components = Counter(r.get("component", "unknown") for r in resolutions)
    severities = Counter(r.get("severity", "unknown") for r in resolutions)
    statuses = Counter(r.get("status", "unknown") for r in resolutions)

    # Platform distribution (platforms is a list field)
    platforms = Counter()
    for r in resolutions:
        for p in (r.get("platform") or []):
            platforms[p] += 1

    # Mean time to resolve (for entries with both timestamps)
    resolve_times = []
    for r in resolutions:
        if r.get("resolved_at") and r.get("report_id"):
            try:
                resolved = datetime.fromisoformat(r["resolved_at"].replace("Z", "+00:00"))
                # Use resolved_at as proxy; real MTTR would need reported_at
                resolve_times.append(resolved)
            except (ValueError, TypeError):
                pass

    return {
        "top_components": dict(components.most_common(5)),
        "severity_breakdown": dict(severities),
        "status_breakdown": dict(statuses),
        "platform_distribution": dict(platforms),
        "shipped_count": statuses.get("shipped", 0),
        "pending_count": statuses.get("pending", 0),
        "wontfix_count": statuses.get("wontfix", 0),
    }


def _format_report(analysis, resolutions):
    """Format analysis as a markdown stability report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    rb = (
        ReportBuilder(f"Stability Report — {now}", include_date=False)
        .metadata(
            Total_resolutions=len(resolutions),
            Shipped=analysis["shipped_count"],
            Pending=analysis["pending_count"],
            Wont_Fix=analysis["wontfix_count"],
        )
        .section("Top Failure Components")
        .table(
            ["Component", "Count"],
            sorted(analysis["top_components"].items(), key=lambda x: -x[1]),
        )
        .section("Severity Breakdown")
        .table(
            ["Severity", "Count"],
            [(sev, analysis["severity_breakdown"].get(sev, 0))
             for sev in ["P0", "P1", "P2", "P3"]
             if analysis["severity_breakdown"].get(sev, 0)],
        )
        .section("Platform Distribution")
        .table(
            ["Platform", "Issues"],
            sorted(analysis["platform_distribution"].items(), key=lambda x: -x[1]),
        )
        .line("---")
        .line(f"*Generated by fleet skill `{SKILL_NAME}`*")
    )
    return rb.build()
