[package]
name = "biged-gui"
version = "1.0.0"
edition.workspace = true

[features]
default = ["desktop"]
desktop = ["eframe/default"]
web = ["eframe/glow", "dep:wasm-bindgen"]

[dependencies]
biged-core = { path = "../biged-core" }
eframe = { workspace = true, default-features = false }
egui = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
